### ISSUE TITLE
Error during Kubernetes client initialization, no Auth Provider found for name "azure"

### ISSUE THREAD

**Issue by hmsvigle** [coopernetes/kube-role-gen#10]
Installed on my cluster using `go` as per documentation. 

```sh
kube-role-gen -h
Usage of kube-role-gen:
  -kubeconfig string
        absolute path to kubeconfig file (default "/root/.kube/config")
  -name string
        Override the name of the ClusterRole resource that is generated (default "foo-clusterrole")
  -v    Enable verbose logging
```

Though In an Open cluster, it generates the clusterrole properly. However while testing on my on-prem cluster, it throws bellow exception. Especially when it is an on-premise cluster. 

```sh
$ kube-role-gen -name popeye-clusterrole.yaml -v
2021/02/22 17:31:26 Error during Kubernetes client initialization, no Auth Provider found for name "azure"

```

**Post installation also, does the tool need internet access to generate the clusterrole ?**

**Comment by Heiss** [comment]
Hey,

i have the same error for name "oidc".

**Comment by coopernetes** [comment]
What is the version of Kubernetes on your on-premises cluster? kube-role-gen uses [k8s.io/client-go](https://github.com/kubernetes/client-go) under the covers, which discovers everything against a live running cluster. Is it possible your kubeconfig got corrupted somehow?

Are you using the correct config context? Again, we're relying on client-go to handle the auth against what already exists in the kubeconfig. I don't do anything particularly special (in fact, I largely follow the example [implementation verbatim](https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go#L44-L56)).

As an aside, the `-name` argument is to set the value of `metadata.name` of the actual `ClusterRole` object that gets created & displayed. To save to a file, you can use simple file redirection:

```bash
$ kube-role-gen -name popeye > popeye-clusterrole.yaml
$ kubectl apply -f popeye-clusterrole.yaml 
clusterrole.rbac.authorization.k8s.io/popeye created
```

**Comment by coopernetes** [comment]
Feel free to re-open if you can provide some additional details (like a sanitized kubeconfig) to test against. I unfortunately don't have any oidc providers available to me to validate this myself.
