### ISSUE TITLE
Missing job resources

### ISSUE THREAD

**Issue by posquit0** [coopernetes/kube-role-gen#11]
When I executed `kube-role-gen`, there is no `batch/jobs` in the output. But `batch/cronjobs` exists.

**Comment by coopernetes** [comment]
Hmm, I wrote a quick rego test for this and couldn't reproduce. Both types of `batch` resources show up in the generated role.

```bash

```

Do you see jobs listed under `kubectl api-resources`? This tool uses [client-go](https://github.com/kubernetes/client-go) and relies on resource discovery of the API server. 

Note, I do see a duplicate set of policy rules (batch/cronjobs shows up twice). Will open a bug for that.
